# Generated by Django 5.0.2 on 2025-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0004_alumnos_creation_alumnos_curp_alumnos_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='password',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='id_matricula',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='materias_impartidas',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='password',
        ),
        migrations.AddField(
            model_name='maestros',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='id_trabajador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
