# Generated by Django 5.0.2 on 2025-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0005_remove_alumnos_email_remove_alumnos_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_realizacion', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('cupoAsistentes', models.PositiveIntegerField()),
                ('programaEducativo', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('publico_objetivo', models.CharField(max_length=255)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
